"""Generating the Alembic scaffold (viur.models.scaffold)."""
import configparser
import pathlib

import pytest

from viur.models import scaffold as scaffold_module
from viur.models.scaffold import FILES, generate, is_complete


def test_writes_the_whole_scaffold(tmp_path):
    created = generate(tmp_path, app_dir=tmp_path / "deploy")
    assert created == list(FILES)
    assert is_complete(tmp_path)
    for name in FILES:
        assert (tmp_path / name).exists()


def test_is_complete_is_false_while_anything_is_missing(tmp_path):
    assert not is_complete(tmp_path)
    generate(tmp_path, app_dir=tmp_path / "deploy")
    (tmp_path / "migrations" / "env.py").unlink()
    assert not is_complete(tmp_path)


def test_existing_files_are_never_overwritten(tmp_path):
    generate(tmp_path, app_dir=tmp_path / "deploy")
    (tmp_path / "alembic.ini").write_text("# hand-edited\n")
    assert generate(tmp_path, app_dir=tmp_path / "deploy") == []
    assert (tmp_path / "alembic.ini").read_text() == "# hand-edited\n"


def test_only_the_missing_files_are_written(tmp_path):
    generate(tmp_path, app_dir=tmp_path / "deploy")
    (tmp_path / "migrations" / "README").unlink()
    assert generate(tmp_path, app_dir=tmp_path / "deploy") == ["migrations/README"]


def test_ini_is_parseable_and_points_at_the_generate(tmp_path):
    generate(tmp_path, app_dir=tmp_path / "deploy")
    # ``%(here)s`` is Alembic's own interpolation variable — it sets it to the
    # ini's directory, so the test has to as well.
    parser = configparser.ConfigParser(defaults={"here": str(tmp_path)})
    parser.read(tmp_path / "alembic.ini")
    section = parser["alembic"]
    assert section["script_location"] == f"{tmp_path}/migrations"
    assert section["prepend_sys_path"] == f"{tmp_path}/deploy"
    # Empty on purpose — resolve_url() decides, see migrations.py.
    assert section["sqlalchemy.url"] == ""
    # %% in the raw file, one % after interpolation.
    assert "%(rev)s" in section["file_template"]


@pytest.mark.parametrize("app_dir, expected", [
    ("deploy", "%(here)s/deploy"),
    ("", "%(here)s"),
    ("nested/dist", "%(here)s/nested/dist"),
])
def test_sys_path_is_relative_to_the_ini(tmp_path, app_dir, expected):
    root = tmp_path / "project"
    root.mkdir()
    assert scaffold_module._sys_path_entry(
        root, (root / app_dir) if app_dir else root,
    ) == expected


def test_sys_path_falls_back_to_absolute_when_outside_the_root(tmp_path):
    root = tmp_path / "project"
    outside = tmp_path / "elsewhere"
    assert scaffold_module._sys_path_entry(root, outside) == outside.as_posix()


def test_env_py_names_the_configured_modules(tmp_path):
    generate(tmp_path, models_package="sqlmodels", settings_module="dbconf")
    env = (tmp_path / "migrations" / "env.py").read_text()
    assert "import dbconf" in env
    assert 'migrations.import_models("sqlmodels")' in env
    assert "fallback_url=dbconf.url()" in env
    compile(env, "env.py", "exec")  # it has to be valid Python


def test_env_py_defaults_to_the_conventional_names(tmp_path):
    generate(tmp_path)
    env = (tmp_path / "migrations" / "env.py").read_text()
    assert "import models_db" in env
    assert 'migrations.import_models("models")' in env


def test_revision_template_imports_sqlmodel(tmp_path):
    """Without it every autogenerated revision dies with NameError."""
    generate(tmp_path)
    template = (tmp_path / "migrations" / "script.py.mako").read_text()
    assert "\nimport sqlmodel\n" in template


def test_revision_template_keeps_its_mako_placeholders(tmp_path):
    generate(tmp_path)
    template = (tmp_path / "migrations" / "script.py.mako").read_text()
    for placeholder in (
        "${message}", "${up_revision}", "${down_revision | comma,n}",
        "${create_date}", "${imports if imports else \"\"}",
        "${repr(branch_labels)}", "${upgrades if upgrades else \"pass\"}",
    ):
        assert placeholder in template


def test_versions_directory_is_git_trackable(tmp_path):
    """Git does not track empty directories, and Alembic needs this one."""
    generate(tmp_path)
    keep = tmp_path / "migrations" / "versions" / ".gitkeep"
    assert keep.is_file() and keep.read_text() == ""


def test_root_is_created_when_missing(tmp_path):
    root = tmp_path / "brand" / "new"
    generate(root)
    assert is_complete(root)


def test_accepts_path_like_and_str(tmp_path):
    generate(str(tmp_path / "a"))
    generate(pathlib.Path(tmp_path / "b"))
    assert is_complete(tmp_path / "a") and is_complete(tmp_path / "b")
