"""Boot wiring: ``install()`` before ``core.setup()``, ``setup()`` after."""
import contextlib
import logging
import os
import pathlib
import typing as t

from sqlmodel import SQLModel

from .config import install_config
from .db import configure_from_conf, get_engine, schema_revision
from .scaffold import generate as generate_scaffold

if t.TYPE_CHECKING:  # pragma: no cover
    from sqlalchemy.engine import Engine

#: ``conf.models`` attributes ``install`` sets, in argument order.
CONF_SETTINGS = ("engine", "sqlite_file", "postgres_dsn", "bigquery_dsn", "engine_options")

logger = logging.getLogger(__name__)


def install(
    *,
    engine: str | None = None,
    sqlite_file: str | None = None,
    postgres_dsn: str | None = None,
    bigquery_dsn: str | None = None,
    engine_options: dict | None = None,
    refresh_hooks: bool = True,
    **refresh_hook_kwargs: t.Any,
) -> "Engine":
    """Attach ``conf.models``, apply the settings, build the engine, install the
    refresh hooks. Once, before ``core.setup()``. ``None`` leaves a setting untouched.

    :param engine: Preset ``"memory"`` / ``"sqlite"`` / ``"postgres"`` / ``"bigquery"``.
    :param engine_options: Extra ``create_engine`` kwargs.
    :param refresh_hooks: ``False`` skips ``install_refresh_hooks``.
    :param refresh_hook_kwargs: Passed to ``install_refresh_hooks``.
    """
    from .crossstore import install_refresh_hooks

    config = install_config()
    for name, value in zip(
        CONF_SETTINGS,
        (engine, sqlite_file, postgres_dsn, bigquery_dsn, engine_options),
    ):
        if value is not None:
            setattr(config, name, value)

    sql_engine = configure_from_conf()

    if refresh_hooks:
        install_refresh_hooks(**refresh_hook_kwargs)
    return sql_engine


def is_dev_server() -> bool:
    """``conf.instance.is_dev_server``, else ``$GAE_ENV == "localdev"``."""
    try:
        from viur.core import conf
    except ImportError:  # pragma: no cover
        return os.environ.get("GAE_ENV") == "localdev"
    instance = getattr(conf, "instance", None)
    return bool(getattr(instance, "is_dev_server", os.environ.get("GAE_ENV") == "localdev"))


def setup(
    engine: "Engine | None" = None,
    *,
    migrations: str | os.PathLike | None = None,
    initial_revision: bool = True,
    **scaffold_kwargs: t.Any,
) -> str | None:
    """Report the schema revision; after ``core.setup()``. Memory preset: ``create_all``.
    ``migrations`` generates the missing Alembic scaffold (dev server only) and, if it
    generated any, the first revision.

    :param engine: Engine to inspect (default: the configured one).
    :param migrations: Directory for ``alembic.ini`` + ``migrations/``; ``None`` generates nothing.
    :param initial_revision: ``False`` leaves the first revision to the developer.
    :param scaffold_kwargs: Passed to ``scaffold.generate``.
    :returns: Stamped revision, or ``None`` (memory preset / unmigrated).
    """
    if migrations is not None and _ensure_scaffold(migrations, **scaffold_kwargs) \
            and initial_revision:
        _bootstrap_revision(migrations)

    engine = engine or get_engine()
    preset = getattr(install_config(), "engine", None)

    if preset == "memory":
        if not SQLModel.metadata.tables:
            logger.warning(
                "viur-models: setup() found an empty SQLModel.metadata — no "
                "model was imported yet, so the in-memory database stays "
                "empty. Call setup() after core.setup()."
            )
        SQLModel.metadata.create_all(engine)
        return None

    revision = schema_revision(engine)
    if revision is None:
        logger.error(
            "viur-models: the SQL schema is not migrated (no alembic_version "
            "table). Run `alembic upgrade head` where alembic.ini lives."
        )
    else:
        logger.info("viur-models: SQL schema at revision %s", revision)
    return revision


def _ensure_scaffold(root: str | os.PathLike, **scaffold_kwargs: t.Any) -> list[str]:
    """Generate missing scaffold files on the dev server; ``OSError`` is logged. Returns created paths."""
    if not is_dev_server():
        return []
    try:
        created = generate_scaffold(root, **scaffold_kwargs)
    except OSError as exc:
        logger.warning("viur-models: could not write the Alembic scaffold: %s", exc)
        return []
    if created:
        logger.info(
            "viur-models: generated the Alembic scaffold in %s (%s)",
            root, ", ".join(created),
        )
    return created


def _bootstrap_revision(root: str | os.PathLike) -> str | None:
    """Autogenerate the first revision: upgrade an empty database, stamp a populated one
    (autogenerated against an empty probe). Errors are logged. Returns ``"upgrade"``,
    ``"stamp"`` or ``None``."""
    try:
        from alembic import command
        from alembic.config import Config
    except ImportError:
        logger.warning(
            "viur-models: generated the Alembic scaffold but cannot apply it — "
            "alembic is not installed (pip install 'spltz-viur-models[migrations]')."
        )
        return None

    config = Config(str(pathlib.Path(root) / "alembic.ini"))
    try:
        populated = _has_model_tables()
        scoped = (
            _autogenerate_against_empty_db(config) if populated else _unchanged(config)
        )
        with scoped as revision_config:
            command.revision(revision_config, message="initial", autogenerate=True)
        if populated:
            command.stamp(config, "head")
        else:
            command.upgrade(config, "head")
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "viur-models: could not apply the generated scaffold (%s: %s) — "
            "run `alembic upgrade head` in %s", type(exc).__name__, exc, root,
        )
        return None

    if populated:
        logger.info(
            "viur-models: generated the initial migration and stamped the "
            "existing database with it (no schema change)"
        )
        return "stamp"
    logger.info("viur-models: generated and applied the initial migration")
    return "upgrade"


def _has_model_tables() -> bool:
    """Whether the database already contains any table the models declare."""
    from sqlalchemy import inspect

    existing = set(inspect(get_engine()).get_table_names())
    return bool(existing & set(SQLModel.metadata.tables))


@contextlib.contextmanager
def _unchanged(config: t.Any) -> t.Iterator[t.Any]:
    """Pass ``config`` through (empty-database arm)."""
    yield config


@contextlib.contextmanager
def _autogenerate_against_empty_db(config: t.Any) -> t.Iterator[t.Any]:
    """Yield a ``copy.copy`` of ``config`` whose ``-x url`` points at a throwaway SQLite
    database, so the revision carries the full ``CREATE``. The caller's config is never mutated."""
    import argparse
    import copy
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        probe = pathlib.Path(tmp) / "empty.sqlite3"
        scoped = copy.copy(config)
        scoped.cmd_opts = argparse.Namespace(x=[f"url=sqlite:///{probe}"])
        yield scoped
