"""Alembic scaffold generator (``alembic.ini`` + ``migrations/``); never overwrites."""
import os
import pathlib

MIGRATIONS_DIRNAME = "migrations"
VERSIONS_DIRNAME = "versions"

ALEMBIC_INI = '''\
# Generated by viur.models.scaffold. An existing file is never rewritten.

[alembic]
script_location = %(here)s/{migrations_dirname}

# The distribution folder, so env.py can import ``{models_package}`` and ``{settings_module}``.
prepend_sys_path = {sys_path}

path_separator = os

file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# Resolved by viur.models.migrations.resolve_url:
# -x url=... > $VIUR_MODELS_DSN > the configured engine > conf.models >
# the env.py fallback. Set here to pin one database for every invocation.
sqlalchemy.url =
'''

ENV_PY = '''\
"""Alembic environment — generated by viur.models.scaffold.

Resolves the database without booting viur-core: the settings come from the
framework-free ``{settings_module}`` module.
"""
from viur.models import migrations

import {settings_module}

# Fills SQLModel.metadata; without it autogenerate would drop every table.
migrations.import_models("{models_package}")

migrations.run(fallback_url={settings_module}.url())
'''

README = '''\
Alembic scaffold for the viur-models SQL schema.
Generated by viur.models.scaffold; existing files are never rewritten.

Run from the directory holding alembic.ini:

    alembic revision --autogenerate -m "add slug to entry"
    alembic upgrade head
    alembic check          # do models and schema still agree?

versions/ holds the revisions; commit them. Bone-level model changes also get
a generated data migration — see docs/migrations.md.
'''


def _script_mako() -> str:
    """Revision template; assembled so mako ``${…}`` survives Python formatting."""
    d = "$"
    return f'''\
"""{d}{{message}}

Revision ID: {d}{{up_revision}}
Revises: {d}{{down_revision | comma,n}}
Create Date: {d}{{create_date}}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate renders column types as sqlmodel.sql.sqltypes.AutoString(...).
import sqlmodel
{d}{{imports if imports else ""}}

# revision identifiers, used by Alembic.
revision: str = {d}{{repr(up_revision)}}
down_revision: Union[str, Sequence[str], None] = {d}{{repr(down_revision)}}
branch_labels: Union[str, Sequence[str], None] = {d}{{repr(branch_labels)}}
depends_on: Union[str, Sequence[str], None] = {d}{{repr(depends_on)}}


def upgrade() -> None:
    """Upgrade schema."""
    {d}{{upgrades if upgrades else "pass"}}


def downgrade() -> None:
    """Downgrade schema."""
    {d}{{downgrades if downgrades else "pass"}}
'''


#: Files ``generate`` writes, relative to ``root``.
FILES = (
    "alembic.ini",
    f"{MIGRATIONS_DIRNAME}/env.py",
    f"{MIGRATIONS_DIRNAME}/script.py.mako",
    f"{MIGRATIONS_DIRNAME}/README",
    f"{MIGRATIONS_DIRNAME}/{VERSIONS_DIRNAME}/.gitkeep",
)


def _sys_path_entry(root: pathlib.Path, app_dir: pathlib.Path) -> str:
    """``prepend_sys_path`` for ``app_dir``: ``%(here)s``-relative, absolute outside ``root``."""
    if app_dir == root:
        return "%(here)s"
    try:
        return f"%(here)s/{app_dir.relative_to(root).as_posix()}"
    except ValueError:
        return app_dir.as_posix()


def generate(
    root: str | os.PathLike,
    *,
    app_dir: str | os.PathLike | None = None,
    models_package: str = "models",
    settings_module: str = "models_db",
) -> list[str]:
    """Write the missing scaffold files into ``root``.

    :param app_dir: Distribution folder for ``prepend_sys_path`` (default: cwd).
    :param models_package: Package ``env.py`` imports to fill ``SQLModel.metadata``.
    :param settings_module: Module providing the ``url()`` fallback.
    :returns: Created paths relative to ``root``.
    """
    root = pathlib.Path(root).resolve()
    app_dir = pathlib.Path(app_dir).resolve() if app_dir else pathlib.Path.cwd()
    fields = {
        "migrations_dirname": MIGRATIONS_DIRNAME,
        "models_package": models_package,
        "settings_module": settings_module,
        "sys_path": _sys_path_entry(root, app_dir),
    }
    contents = {
        "alembic.ini": ALEMBIC_INI.format(**fields),
        f"{MIGRATIONS_DIRNAME}/env.py": ENV_PY.format(**fields),
        f"{MIGRATIONS_DIRNAME}/script.py.mako": _script_mako(),
        f"{MIGRATIONS_DIRNAME}/README": README,
        f"{MIGRATIONS_DIRNAME}/{VERSIONS_DIRNAME}/.gitkeep": "",
    }

    created = []
    for name in FILES:
        path = root / name
        if path.exists():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents[name], encoding="utf-8")
        created.append(name)
    return created


def is_complete(root: str | os.PathLike) -> bool:
    """Whether ``root`` holds every scaffold file."""
    root = pathlib.Path(root)
    return all((root / name).exists() for name in FILES)
